version: '3.1'

services:
  web:
    image: dikorsch/randomizer:latest
    restart: unless-stopped

    command: bash 20_run_server.sh

    expose:
      - "${PORT:-8000}"

    volumes:
      # mount code folder
      - .:/code:rw

    env_file:
      - dockerenv

  nginx:
    image: nginx:latest

    ports:
      - "8000:8000"

    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/code/static

    depends_on:
      - web

