version: '3.1'

services:
  web:
    image: dikorsch/randomizer:latest
    restart: unless-stopped

    command: bash 20_run_server.sh

    ports:
      - "8000:${PORT:-8000}"

    volumes:
      # mount code folder
      - .:/code:ro
      - ./static:/code/static:rw

    env_file:
      - dockerenv

